name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Check go version
      run: go version
    
#    - name: configure
#      run: ./configure
      
    - name: Test submodules before code integration
      run: make test

    - name: Make all
      run: make all

#    - name: Run check
#      run: make check
#
#    - name: Run distcheck
#      run: make distcheck
